// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dna
IntegerVector dna(std::string s);
RcppExport SEXP _rosalindRcpp_dna(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(dna(s));
    return rcpp_result_gen;
END_RCPP
}
// fib
long long int fib(int n, int k);
RcppExport SEXP _rosalindRcpp_fib(SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(fib(n, k));
    return rcpp_result_gen;
END_RCPP
}
// gc
NumericVector gc(std::string file_path);
RcppExport SEXP _rosalindRcpp_gc(SEXP file_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file_path(file_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(gc(file_path));
    return rcpp_result_gen;
END_RCPP
}
// hello_world
String hello_world(String your_name);
RcppExport SEXP _rosalindRcpp_hello_world(SEXP your_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type your_name(your_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(hello_world(your_name));
    return rcpp_result_gen;
END_RCPP
}
// parse_fasta
List parse_fasta(std::string file_path);
RcppExport SEXP _rosalindRcpp_parse_fasta(SEXP file_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file_path(file_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_fasta(file_path));
    return rcpp_result_gen;
END_RCPP
}
// revc
std::string revc(std::string s);
RcppExport SEXP _rosalindRcpp_revc(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(revc(s));
    return rcpp_result_gen;
END_RCPP
}
// rna
std::string rna(std::string t);
RcppExport SEXP _rosalindRcpp_rna(SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(rna(t));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rosalindRcpp_dna", (DL_FUNC) &_rosalindRcpp_dna, 1},
    {"_rosalindRcpp_fib", (DL_FUNC) &_rosalindRcpp_fib, 2},
    {"_rosalindRcpp_gc", (DL_FUNC) &_rosalindRcpp_gc, 1},
    {"_rosalindRcpp_hello_world", (DL_FUNC) &_rosalindRcpp_hello_world, 1},
    {"_rosalindRcpp_parse_fasta", (DL_FUNC) &_rosalindRcpp_parse_fasta, 1},
    {"_rosalindRcpp_revc", (DL_FUNC) &_rosalindRcpp_revc, 1},
    {"_rosalindRcpp_rna", (DL_FUNC) &_rosalindRcpp_rna, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rosalindRcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
