# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dna <- function(s) {
    .Call(`_rosalindRcpp_dna`, s)
}

#' Combine "Hello world" and `your_name` and return it as a string
#'
#' @description
#' This is only a test.
#'
#' @param your_name Your name
#'
#' @return A string containing "Hello world", combined with your name
#' @export
hello_world <- function(your_name) {
    .Call(`_rosalindRcpp_hello_world`, your_name)
}

revc <- function(s) {
    .Call(`_rosalindRcpp_revc`, s)
}

rna <- function(t) {
    .Call(`_rosalindRcpp_rna`, t)
}

