# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Solution for Problem "Counting DNA Nucleotides"
#'
#' @description
#' Counts DNA nucleotides in sequence `s` and returns the number of A, C, G and T in that order. Letters other than A, C, G and T will be ignored.
#'
#' @param s A string holding the sequence.
#'
#' @return A vector with the number of A, C, G and T in that order.
#' @export
dna <- function(s) {
    .Call(`_rosalindRcpp_dna`, s)
}

fib <- function(n, k) {
    .Call(`_rosalindRcpp_fib`, n, k)
}

#' Combine "Hello world" and `your_name` and return it as a string
#'
#' @description
#' This is only a test.
#'
#' @param your_name Your name
#'
#' @return A string containing "Hello world", combined with your name
#' @export
hello_world <- function(your_name) {
    .Call(`_rosalindRcpp_hello_world`, your_name)
}

parse_fasta <- function(file_path) {
    .Call(`_rosalindRcpp_parse_fasta`, file_path)
}

revc <- function(s) {
    .Call(`_rosalindRcpp_revc`, s)
}

rna <- function(t) {
    .Call(`_rosalindRcpp_rna`, t)
}

