# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Return "Hello world" as a string
#'
#' @description
#' This is only a test.
#'
#' @return A string containing "Hello world"
#' @export
hello_world <- function() {
    .Call(`_rosalindRcpp_hello_world`)
}

